import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-svh flex flex-col ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="fixed top-0 left-0 right-0 z-10 bg-background border-b border-muted">
          <h1 className="max-w-3xl mx-auto font-bold p-4 uppercase">
            <nav>
              <ul className="flex gap-4">
                <li>
                  <Link href="/">A Blog Example</Link>
                </li>
              </ul>
            </nav>
          </h1>
        </header>
        <main className="w-full max-w-3xl mx-auto flex-1 mt-12 mb-4 p-4 lg:mt-20">
          {children}
        </main>
        <footer className="bg-background border-t border-muted text-secondary text-sm">
          <div className="max-w-3xl mx-auto p-4">
            Made by{" "}
            <Link href="https://arnaudrenaud.com" className="underline">
              Arnaud Renaud
            </Link>
          </div>
        </footer>
      </body>
    </html>
  );
}
